import re

file_path = 'scripts/parse_data_v4.py'
with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

start_line = None
end_line = None
for i, line in enumerate(lines):
    if '    content_blocks = []' in line and i > 1000:
        start_line = i
    if start_line is not None and 'result["content_blocks"] = content_blocks' in line:
        end_line = i
        break

if start_line and end_line:
    print(f"Found section from line {start_line+1} to {end_line}")
    
    new_code = '''    content_blocks = []
    # 先添加子页面链接（放在最前面）
    if sub_pages:
        content_blocks.append({
            "type": "sub_pages",
            "title": f"相关旗帜（{len(sub_pages)}个）",
            "links": sub_pages
        })

    # 提取段落文本，过滤模板内容
    boilerplate_patterns = [
        r'last\\s+modified', r'keywords?:', r'^return\\s+to', r'anything below this line',
        r'was not added by the editor', r'please report any errors',
        r'form for reporting errors', r'generated by'
    ]
    boilerplate_re = re.compile('|'.join(boilerplate_patterns), re.I)

    p_pattern = r'<p[^>]*>(.*?)</p>'
    para_count = 0
    for m in re.finditer(p_pattern, html_content, re.I | re.DOTALL):
        p_text = clean_text(unescape(re.sub(r'<[^>]+>', '', m.group(1))))
        if len(p_text) > 30 and not boilerplate_re.search(p_text):
            content_blocks.append({"type": "paragraph", "text": p_text})
            para_count += 1
            if para_count >= 5:
                break

    if not sub_pages and para_count == 0 and result.get("title"):
        content_blocks.append({
            "type": "paragraph",
            "text": f"这是「{result['title']}」的分类索引页面。"
        })

'''
    
    new_lines = lines[:start_line] + [new_code] + lines[end_line:]
    
    with open(file_path, 'w', encoding='utf-8') as f:
        f.writelines(new_lines)
    
    print("SUCCESS: File patched")
else:
    print(f"Could not find section: start={start_line}, end={end_line}")
